### ISSUE TITLE
[Reported] Getting NoneType when calling project.lead.key

### ISSUE THREAD

**Issue by betsythefc** [betsythefc/joca#1]
```
Traceback (most recent call last):
  File "/usr/local/bin/joca", line 216, in <module>
    main()
  File "/usr/local/bin/joca", line 201, in main
    current_lead_key = get_current_project_lead(jira_config)
  File "/usr/local/bin/joca", line 67, in get_current_project_lead
    logging.info("Current project lead: %s", project.lead.key)
  File "/usr/local/lib/python2.7/dist-packages/jira/resources.py", line 170, in __getattr__
    if hasattr(self, 'raw') and item in self.raw:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by betsythefc** [comment]
Fixed with commit https://github.com/betsythefc/joca/commit/dc9eb9a9d79967cae7701f08c700d601030a8205
